"""Health Insights - Long context analysis with Gemma 4."""

import streamlit as st
import json
from datetime import datetime, timedelta


def render_insights_page(gemma_client, dataset_manager, user_profile):
    """Comprehensive health insights using long context."""
    st.subheader("🔍 Comprehensive Health Insights")
    st.caption("AI-powered analysis of your entire postpartum journey")

    st.info(f"Hi {user_profile['name']}! This feature analyzes ALL your data together using advanced AI.")

    # Load all data
    from app.crewai_flow import PostpartumFlow
    flow = PostpartumFlow(dm=dataset_manager, gc=gemma_client)

    tracker_history = flow.get_tracker_history()
    journal_entries = st.session_state.get("journal_entries", [])
    chat_history = st.session_state.get("chat_history", [])

    # Data summary
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Health Entries", len(tracker_history))
    with col2:
        st.metric("Journal Entries", len(journal_entries))
    with col3:
        st.metric("Chat Messages", len(chat_history))
    with col4:
        st.metric("Days Postpartum", user_profile['postpartum_days'])

    st.markdown("---")

    # Analysis type
    analysis_type = st.selectbox(
        "What would you like to analyze?",
        [
            "📊 Overall Health Trends",
            "🧠 Mental Health & Emotional Wellbeing",
            "💪 Physical Recovery Progress",
            "🍽️ Nutrition & Diet Patterns",
            "😴 Sleep Quality Analysis",
            "📈 Risk Assessment & Red Flags",
            "🎯 Personalized Recommendations",
            "📝 Custom Question"
        ]
    )

    # Custom question input
    custom_question = None
    if analysis_type == "📝 Custom Question":
        custom_question = st.text_area(
            "Ask anything about your health journey",
            placeholder="e.g., How has my mood changed over time? Are my symptoms improving?"
        )

    # Generate button
    if st.button("🔍 Generate Insights", type="primary", use_container_width=True):
        if analysis_type == "📝 Custom Question" and not custom_question:
            st.warning("Please enter your question")
            return

        # Build comprehensive context
        with st.spinner("Analyzing your entire health journey... This may take a moment."):
            context = _build_long_context(
                user_profile, tracker_history, journal_entries, chat_history
            )

            # Build question based on analysis type
            questions = {
                "📊 Overall Health Trends": "Analyze overall health trends across all metrics. Identify patterns, improvements, and areas of concern.",
                "🧠 Mental Health & Emotional Wellbeing": "Focus on mental health and emotional wellbeing. Analyze journal entries, mood patterns, and emotional indicators. Screen for postpartum depression signs.",
                "💪 Physical Recovery Progress": "Assess physical recovery progress. Analyze vitals, sleep, physical symptoms, and recovery milestones.",
                "🍽️ Nutrition & Diet Patterns": "Evaluate nutrition and diet patterns. Identify deficiencies, good habits, and suggestions for improvement.",
                "😴 Sleep Quality Analysis": "Analyze sleep patterns and quality. Identify factors affecting sleep and suggest improvements.",
                "📈 Risk Assessment & Red Flags": "Perform comprehensive risk assessment. Flag any concerning patterns or red flags that need medical attention.",
                "🎯 Personalized Recommendations": "Generate personalized action plan with specific, actionable recommendations for next 7 days.",
                "📝 Custom Question": custom_question
            }

            question = questions[analysis_type]

            try:
                # Use long context generation
                response = gemma_client.generate_long_context(
                    context=context,
                    question=f"{question}\n\nProvide detailed insights in {st.session_state.language}. Be warm and supportive.",
                    max_new_tokens=1024
                )

                st.markdown(f"### {analysis_type}")
                st.write(response)

                # Export option
                st.markdown("---")
                col1, col2 = st.columns([3, 1])
                with col2:
                    export_text = f"""
Health Insights Report
Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}

Patient: {user_profile['name']}
Days Postpartum: {user_profile['postpartum_days']}
Analysis Type: {analysis_type}

{response}

---
Generated by Postpartum Care Companion
This is an AI-generated insight. Consult healthcare provider for medical decisions.
"""
                    st.download_button(
                        "📥 Download Report",
                        data=export_text,
                        file_name=f"health_insights_{datetime.now().strftime('%Y%m%d')}.txt",
                        mime="text/plain"
                    )

            except Exception as e:
                st.error(f"❌ Analysis failed: {str(e)}")
                st.warning("Try analyzing a shorter time period or contact support.")

    # Quick insights section
    st.markdown("---")
    st.markdown("### 💡 Quick Insights")

    if tracker_history:
        col1, col2 = st.columns(2)

        with col1:
            # Latest vitals
            latest = tracker_history[-1]
            st.markdown("**Latest Readings:**")
            if latest.get("bp_systolic"):
                st.write(f"🩸 BP: {latest['bp_systolic']}/{latest.get('bp_diastolic', 0)} mmHg")
            if latest.get("sleep_hours"):
                st.write(f"😴 Sleep: {latest['sleep_hours']} hours")
            if latest.get("mood"):
                st.write(f"😊 Mood: {latest['mood']}")

        with col2:
            # Recent trends
            st.markdown("**Recent Activity:**")
            st.write(f"📅 Last tracked: {latest.get('date', 'N/A')}")
            st.write(f"📊 Total entries: {len(tracker_history)}")

            # Alert count
            from app.crewai_flow import _flag_alerts
            recent_alerts = sum(1 for e in tracker_history[-7:] if _flag_alerts(e))
            if recent_alerts > 0:
                st.warning(f"⚠️ {recent_alerts} alerts in past week")
    else:
        st.info("Start tracking your health to see insights here!")

    # Educational section
    with st.expander("ℹ️ How does this work?"):
        st.markdown("""
**Long Context Analysis**

This feature uses Gemma 4's advanced 128K context window to analyze:
- ✅ All your health tracker entries
- ✅ All journal entries
- ✅ Complete chat history with Ira
- ✅ Your user profile and preferences

**Benefits:**
1. **Holistic view**: Sees patterns across all your data
2. **Temporal analysis**: Tracks changes over time
3. **Comprehensive insights**: Considers everything together
4. **Personalized**: Tailored to your specific journey

**Privacy:** All analysis happens securely. Your data is never shared externally.
""")


def _build_long_context(profile, tracker_data, journals, chats):
    """Build comprehensive context string for long-context analysis."""

    context = f"""
# Patient Profile
Name: {profile.get('name')}
Age: {profile.get('age')}
Days Postpartum: {profile.get('postpartum_days')}
Number of Children: {profile.get('num_children')}
Working Status: {profile.get('working_status')}
Delivery Type: {profile.get('delivery_type')}
Feeding Method: {profile.get('feeding_method')}
Current Phase: {profile.get('phase').replace('_', ' ').title()}

---

# Health Tracker History ({len(tracker_data)} entries)

"""

    # Add tracker data (summarized if too long)
    for entry in tracker_data[-50:]:  # Last 50 entries
        context += f"\n**{entry.get('date', 'N/A')}**\n"
        if entry.get('bp_systolic'):
            context += f"- BP: {entry['bp_systolic']}/{entry.get('bp_diastolic', 0)} mmHg\n"
        if entry.get('sleep_hours'):
            context += f"- Sleep: {entry['sleep_hours']} hours\n"
        if entry.get('mood'):
            context += f"- Mood: {entry['mood']}\n"
        if entry.get('notes'):
            context += f"- Notes: {entry['notes']}\n"

    context += "\n---\n\n# Journal Entries\n\n"

    # Add journal entries
    for i, journal in enumerate(journals[-20:], 1):  # Last 20 entries
        context += f"\n**Entry {i}** ({journal.get('timestamp')})\n{journal.get('text')}\n"
        if journal.get('analysis'):
            context += f"Analysis: {journal['analysis']}\n"

    context += "\n---\n\n# Chat History (Recent Conversations)\n\n"

    # Add recent chat history
    for turn in chats[-30:]:  # Last 30 exchanges
        context += f"Mother: {turn['user']}\nIra: {turn['ira']}\n\n"

    context += "\n---\n\nEnd of patient data. Please analyze comprehensively.\n"

    return context
